export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const SAVE_PAGE_DATA = 'SAVE_PAGE_DATA';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const SAVE_EVENTS_DATA = 'SAVE_EVENTS_DATA';
export const UPDATE_MYSCHEDULE = 'UPDATE_MYSCHEDULE';